from typing import Union
from interfaces.models import Activity, Buddy


def _as_buddy(b: Union[Buddy, dict]) -> Buddy:
    return Buddy.model_validate(b) if isinstance(b, dict) else b


def build_invite_preview_card(activity: Activity, buddies: list[Buddy], invite_message_preview: str) -> dict:
    """Card shown after buddy selection — displays the full plan and a preview of the invite message.

    User can 'Send Invites' (accept_invite) or 'Start Over' (reject_invite).
    The invite_message_preview is LLM-generated by ConfirmationAgent.
    """
    buddy_names = ", ".join(_as_buddy(b).name for b in buddies) if buddies else "Solo adventure"

    elements = [
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": "**📋 Plan Summary**",
            },
        },
        {
            "tag": "div",
            "fields": [
                {"is_short": True, "text": {"tag": "lark_md", "content": f"**Activity**\n{activity.name}"}},
                {"is_short": True, "text": {"tag": "lark_md", "content": f"**Type**\n{activity.type.capitalize()}"}},
                {"is_short": True, "text": {"tag": "lark_md", "content": f"**Budget**\n{activity.budget.value.capitalize()}"}},
                {"is_short": True, "text": {"tag": "lark_md", "content": f"**Vibe**\n{activity.vibe.value.capitalize()}"}},
            ],
        },
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": f"**👥 Attendees**\n{buddy_names}",
            },
        },
        {"tag": "hr"},
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": "**✉️ Invite Message Preview**",
            },
        },
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": f"_{invite_message_preview}_",
            },
        },
        {"tag": "hr"},
        {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": "Send Invites ✉️"},
                    "type": "primary",
                    "value": {"action": "accept_invite"},
                },
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": "Start Over 🔄"},
                    "type": "danger",
                    "value": {"action": "reject_invite"},
                },
            ],
        },
    ]

    return {
        "config": {"wide_screen_mode": True},
        "header": {
            "title": {"tag": "plain_text", "content": "📬 Ready to Send Invites?"},
            "template": "blue",
        },
        "elements": elements,
    }


def build_confirmation_card(activity: Activity, buddies: list[Buddy]) -> dict:
    """Build a Lark interactive card for confirming the final plan."""
    buddy_names = ", ".join(b.name for b in buddies) if buddies else "Solo adventure"

    elements = [
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": (
                    f"**Activity**: {activity.name}\n"
                    f"**Type**: {activity.type}\n"
                    f"**Budget**: {activity.budget.value}\n"
                    f"**Vibe**: {activity.vibe.value}\n"
                    f"**Buddies**: {buddy_names}"
                ),
            },
        },
        {"tag": "hr"},
        {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": "Confirm Plan ✅"},
                    "type": "primary",
                    "value": {"action": "confirm"},
                },
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": "Cancel ❌"},
                    "type": "danger",
                    "value": {"action": "cancel"},
                },
            ],
        },
    ]

    return {
        "config": {"wide_screen_mode": True},
        "header": {
            "title": {"tag": "plain_text", "content": "📋 Confirm Your Plan"},
            "template": "orange",
        },
        "elements": elements,
    }


def build_confirmed_card(activity: Activity, buddies: list[Buddy]) -> dict:
    """Build a Lark card showing the finalized confirmed plan."""
    buddy_names = ", ".join(b.name for b in buddies) if buddies else "Solo adventure"

    elements = [
        {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": (
                    f"🎉 **Plan Confirmed!**\n\n"
                    f"**Activity**: {activity.name}\n"
                    f"**Type**: {activity.type}\n"
                    f"**Budget**: {activity.budget.value}\n"
                    f"**Vibe**: {activity.vibe.value}\n"
                    f"**Buddies**: {buddy_names}\n\n"
                    f"Have an amazing weekend! 🥳"
                ),
            },
        },
        {"tag": "hr"},
        {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": "Start Over 🔄"},
                    "type": "default",
                    "value": {"action": "reset"},
                },
            ],
        },
    ]

    return {
        "config": {"wide_screen_mode": True},
        "header": {
            "title": {"tag": "plain_text", "content": "✅ Weekend Plan Locked In!"},
            "template": "green",
        },
        "elements": elements,
    }
